AddCSLuaFile();
SWEP.Base = "plutonic_base_melee";
SWEP.PrintName = "Melee Example";
SWEP.Category = "Plutonic";
SWEP.Spawnable = true;
SWEP.AdminOnly = false;
SWEP.HoldType = "melee2";
SWEP.HitAnim = ACT_VM_MISSCENTER;
SWEP.WorldModel = Model("models/weapons/w_crowbar.mdl");
SWEP.ViewModel = Model("models/weapons/v_crowbar.mdl");
SWEP.ViewModelFOV = 74;
SWEP.CenteredPos = Vector(0, 0, 0);
SWEP.CenteredAng = Angle(0, 0, 0);
SWEP.Slot = 4;
SWEP.SlotPos = 1;
SWEP.CSMuzzleFlashes = false;
SWEP.Primary.Sound = Sound("WeaponFrag.Roll");
SWEP.Primary.ImpactSound = Sound("Canister.ImpactHard");
SWEP.Primary.ImpactSoundWorldOnly = true;
SWEP.Primary.Recoil = 1.2; -- base recoil value, SWEP.Spread mods can change this
SWEP.Primary.Damage = 19; -- not used in this swep
SWEP.Primary.NumShots = 1;
SWEP.Primary.HitDelay = 0.3;
SWEP.Primary.Delay = 0.9;
SWEP.Primary.Range = 75;
SWEP.Primary.StunTime = 0.3;
